filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log


output.logstash:
  hosts: [ "workscheduler.logstash:5044" ]


setup.kibana:
  host: "elasticstack.kibana:5601"