version: "3.7"
services:
  mysql:
    build: docker/mysql
    container_name: mysql
    volumes:
      - type: volume
        source: logs
        target: /var/log
    restart: always
    env_file: docker/mysql/.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: workscheduler
      TZ: "Asia/Tokyo"
  uwsgi:
    container_name: uwsgi
    build:
      context: .
      dockerfile: ./docker/workscheduler/Dockerfile
    env_file: 
      - docker/mysql/.env
    ports:
      - "3928:3928"
    links:
      - mysql
    environment:
      TZ: "Asia/Tokyo"
  nginx:
    build: docker/nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"

volumes:
  logs: