version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: workscheduler.mysql
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: dbstorage
        target: /var/lib/mysql
    restart: always
    env_file: mysql/.env
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: workscheduler
      TZ: "Asia/Tokyo"
  uwsgi:
    build: workscheduler
    container_name: workscheduler.uwsgi
    volumes:
      - type: volume
        source: logs
        target: /var/log
    ports:
      - 3928:3928
    environment:
      TZ: "Asia/Tokyo"
  nginx:
    image: nginx:alpine
    container_name: workscheduler.nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - type: volume
        source: logs
        target: /var/log/nginx
    command: /bin/ash -c "nginx -g 'daemon off;'"
    ports:
      - 4231:80
    ulimits:
      nproc: 65535
    environment:
      TZ: "Asia/Tokyo"
  logstash:
    image: logstash:7.3.0
    container_name: workscheduler.logstash
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - ./logstash/conf/:/usr/share/logstash/pipeline
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    networks:
      - elasticstack.elastic

volumes:
  logs:
    name: workscheduler.logs
  dbstorage:
    name: workscheduler.dbstorage

networks:
  default:
    name: workscheduler.default
  elasticstack.elastic:
    external: true
