version: "3"
services:

  mysql:
    build: docker/mysql
    volumes:
      - ./log/mysql:/var/log/mysql
    restart: always
    env_file: docker/mysql/.env
    ports:
      - "3306:3306"
    networks:
      - local-net
    environment:
      MYSQL_DATABASE: workscheduler
      TZ: "Asia/Tokyo"

  uwsgi:
    build:
      context: ./
      dockerfile: docker/workscheduler/Dockerfile
    volumes:
      - ./src:/var/www/src
    env_file: 
      - docker/workscheduler/.env
      - docker/mysql/.env
    links:
      - mysql
    ports:
      - "3928:3928"
    networks:
      - local-net
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: docker/nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"

networks:
  local-net:
    driver: bridge