version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - type: volume
        source: logs
        target: /var/log
      - type: volume
        source: dbstorage
        target: /var/lib/mysql
    restart: always
    env_file: mysql/.env
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: workscheduler
      TZ: "Asia/Tokyo"
  uwsgi:
    build: workscheduler
    container_name: uwsgi
    env_file: 
      - mysql/.env
    ports:
      - 3928:3928
    links:
      - mysql
    environment:
      TZ: "Asia/Tokyo"
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: /bin/ash -c "nginx -g 'daemon off;'"
    links:
      - uwsgi
    ports:
      - 4231:80
    ulimits:
      nproc: 65535
    environment:
      TZ: "Asia/Tokyo"

volumes:
  logs:
  dbstorage: