version: "3"
services:

  uwsgi:
    build: ./workscheduler
    volumes:
      - ./workscheduler:/var/www/
      - ./mypackages:/var/www
    ports:
      - "3928:3928"
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - uwsgi
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"